---
- name: Hello Events
  hosts: rhel1
  sources:
    - ansible.eda.file_watch:
        path: /tmp/test.txt
        recursive: false
#  rules:
#    - name: debug output
#      condition: event.type == "FileModifiedEvent"
#      action:
#        print_event:

  rules:
    - name: EDA | Ping Test
      condition: event.type == "FileModifiedEvent"
      actions:
        - run_job_template:
            name: "PingTest"
            organization: "Default"
