---
- name: Hello Events
  hosts: rhel1
  sources:
    - ansible.eda.file_watch:
        path: /tmp/testing/
        recursive: false
  rules:
    - name: debug output
      condition: event.type == "FileModifiedEvent"
      action:
          print_event:
