---
- name: Listen for events on journald
  hosts: all

  sources:
    - ansible.eda.journald:
        match: "ALL"

  rules:
    - name: EDA | Ping Test
      condition: event.journald.message contains "/tmp/test.txt"
      actions:
        - run_job_template:
            name: "PingTest"
            organization: "Default"
