---
- name: Listen for events on journald
  hosts: rhel1

  sources:
    - ansible.eda.journald:
        match: "ALL"

  rules:
    - name: EDA | Ping Test
      condition: event.type == "FileModifiedEvent"
      actions:
        - run_job_template:
            name: "PingTest"
            organization: "Default"
